"""Train the triage classifier on Dataset 2 and write every artifact the API and the UI read.

Pipeline (see docs/2026-09-16-plano-implementacao.md, Task 4):

1. read ``data/all_tickets_processed_improved_v3.csv`` (47,837 real IT tickets, 8 classes),
   drop near-duplicates by the first 20 words, keep the first occurrence;
2. stratified 80/20 split with seed 42 (ids = 0-based row index of the CSV);
3. TF-IDF (1-2 grams, min_df=2, sublinear, <= 300k features, float32) + multinomial
   logistic regression (C=5);
4. hold-out predictions with confidence and top-3 classes;
5. top-3 nearest training tickets by cosine similarity, computed in blocks of
   ``SIM_BLOCK`` hold-out rows so peak memory stays well under 2 GB;
6. accuracy, macro-F1, per-class report, confusion matrix, ECE, coverage x accuracy
   for every threshold from 0.50 to 0.99, useful coverage after the policy
   (AUTO classes, no risk flag), per-class coverage at 0.80/0.90/0.95, similarity
   curve, optional 5-fold CV;
7. figures, ``holdout_pred.csv.gz`` (replay data), ``policy.json`` and ``models/index.pkl``.

The dataset text is already pre-processed (lowercase, no punctuation/stopwords), so the
vectorizer is fitted on the CSV text as is. ``app.normalize`` is applied by the API to free
text typed by a user, not here.

Outputs:
  models/index.pkl                      (gitignored; regenerated by `make train`)
  artifacts/metrics.json                single source of every number shown in the UI
  artifacts/policy.json                 app.policy.policy_table()
  artifacts/holdout_pred.csv.gz         id, text, true_category, pred_category, confidence,
                                        top3_json, nn_ids_json, nn_sims_json
  artifacts/figures/{confusion,coverage_accuracy,reliability,similarity_curve}.png

Run from the prototype root:  uv run python scripts/train.py [--no-cv5]
"""

from __future__ import annotations

import argparse
import hashlib
import json
try:
    import resource  # Unix only; the script still trains without it
except ImportError:  # pragma: no cover - Windows
    resource = None
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.pipeline import Pipeline

PROTO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROTO))

from app.policy import AUTO, CLASSES, DEFAULT_THRESHOLD, policy_table, risk_flags  # noqa: E402

DATA = PROTO / "data" / "all_tickets_processed_improved_v3.csv"
ART = PROTO / "artifacts"
FIG_DIR = ART / "figures"
MODELS = PROTO / "models"
INDEX = MODELS / "index.pkl"
METRICS = ART / "metrics.json"
POLICY = ART / "policy.json"
HOLDOUT = ART / "holdout_pred.csv.gz"
FIGURES = {
    "confusion": FIG_DIR / "confusion.png",
    "coverage_accuracy": FIG_DIR / "coverage_accuracy.png",
    "reliability": FIG_DIR / "reliability.png",
    "similarity_curve": FIG_DIR / "similarity_curve.png",
}

SEED = 42
TEST_SIZE = 0.2
DEDUP_WORDS = 20
TOP_K = 3
SIM_BLOCK = 2000  # hold-out rows per dense similarity block (block x n_train float32 ~ 0.3 GB)
SIM_CHUNK = 125  # rows per sparse product / top-k inside a block (bounds scipy's nnz upper-bound allocation)
TFIDF_CONFIG = dict(ngram_range=(1, 2), min_df=2, sublinear_tf=True, max_features=300_000)
# n_jobs is intentionally not passed: scikit-learn >= 1.8 ignores it for LogisticRegression.
LOGREG_CONFIG = dict(C=5, max_iter=2000)
THRESHOLDS = np.round(np.arange(0.50, 1.00, 0.01), 2)  # 0.50 .. 0.99
POLICY_THRESHOLDS = (0.80, 0.90, 0.95)
SIM_BINS = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
ECE_BINS = 10
CV_FOLDS = 5
CV_BUDGET_SECONDS = 90  # the plan: cv5 only if it fits in 90 s

TEXT_COL = "Document"
LABEL_COL = "Topic_group"
HOLDOUT_COLUMNS = [
    "id", "text", "true_category", "pred_category", "confidence",
    "top3_json", "nn_ids_json", "nn_sims_json",
]

# Project palette (plan): navy / gold / gray on a white surface, plus status colors.
NAVY = "#001F35"
GOLD = "#B9915B"
GRAY = "#9CA3AF"
GRID = "#E5E7EB"
DANGER = "#B3261E"
INK = "#0b0b0b"
SURFACE = "#FFFFFF"


# --------------------------------------------------------------------------- helpers
def r4(x: float) -> float:
    return round(float(x), 4)


def r6(x: float) -> float:
    return round(float(x), 6)


def mean_or_none(values: np.ndarray) -> float | None:
    return r4(values.mean()) if values.size else None


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def peak_rss_mb() -> float:
    if resource is None:
        return 0.0
    rss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    if sys.platform != "darwin":  # Linux reports kilobytes, macOS bytes
        rss *= 1024
    return round(rss / 1e6, 1)


def pct(x: float) -> str:
    """pt-BR percentage for figure labels."""
    return f"{x:.1%}".replace(".", ",")


# --------------------------------------------------------------------------- data
def load_and_dedup() -> tuple[pd.DataFrame, int, int]:
    """Read Dataset 2 and drop near-duplicates keyed by the first ``DEDUP_WORDS`` words.

    The original 0-based row index is kept as the ticket ``id`` so every prediction
    can be traced back to the CSV line.
    """
    df = pd.read_csv(DATA, usecols=[TEXT_COL, LABEL_COL])
    df[TEXT_COL] = df[TEXT_COL].fillna("").astype(str)
    df[LABEL_COL] = df[LABEL_COL].astype(str)
    n_total = int(len(df))
    unknown = sorted(set(df[LABEL_COL]) - set(CLASSES))
    if unknown:
        sys.exit(f"unexpected classes in {DATA.name}: {unknown}")
    key = df[TEXT_COL].map(lambda s: " ".join(s.split()[:DEDUP_WORDS]))
    keep = ~key.duplicated(keep="first")
    df = df[keep & (df[TEXT_COL].str.strip() != "")]
    n_removed = n_total - int(len(df))
    return df, n_total, n_removed


def split(df: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    """Stratified 80/20 split; returns positional indices into ``df``."""
    positions = np.arange(len(df))
    tr, ho = train_test_split(
        positions, test_size=TEST_SIZE, stratify=df[LABEL_COL].to_numpy(), random_state=SEED
    )
    return np.sort(tr), np.sort(ho)


# --------------------------------------------------------------------------- model
def fit(texts: np.ndarray, labels: np.ndarray) -> tuple[TfidfVectorizer, LogisticRegression, sparse.csr_matrix]:
    vec = TfidfVectorizer(dtype=np.float32, **TFIDF_CONFIG)
    X = vec.fit_transform(texts).tocsr()
    # Older scikit-learn versions keep every pruned term here; it only bloats the pickle.
    if getattr(vec, "stop_words_", None) is not None:
        vec.stop_words_ = None
    clf = LogisticRegression(**LOGREG_CONFIG).fit(X, labels)
    if list(clf.classes_) != CLASSES:
        sys.exit(f"classifier classes {list(clf.classes_)} differ from policy.CLASSES {CLASSES}")
    return vec, clf, X


def predict(clf: LogisticRegression, X: sparse.csr_matrix) -> tuple[np.ndarray, np.ndarray, np.ndarray, list[list[dict]]]:
    proba = clf.predict_proba(X).astype(np.float64)
    order = np.argsort(-proba, axis=1)[:, :3]
    pred = clf.classes_[order[:, 0]]
    # Rounded once, here, so metrics.json and holdout_pred.csv.gz use identical numbers.
    confidence = np.round(proba.max(axis=1), 6)
    top3 = [
        [{"category": str(clf.classes_[j]), "p": r6(proba[i, j])} for j in order[i]]
        for i in range(proba.shape[0])
    ]
    return proba, pred, confidence, top3


def nearest_neighbors(
    X_query: sparse.csr_matrix,
    X_train: sparse.csr_matrix,
    k: int = TOP_K,
    block: int = SIM_BLOCK,
    chunk: int = SIM_CHUNK,
) -> tuple[np.ndarray, np.ndarray]:
    """Top-``k`` cosine neighbors (positions in ``X_train``) computed ``block`` rows at a time.

    TF-IDF rows are already L2-normalized, so the dot product is the cosine. The
    similarity of one block is ~86% dense on this dataset, so it lives in a reused
    dense float32 buffer (block x n_train). The sparse product and the top-k are
    done ``chunk`` rows at a time inside the block: scipy sizes the product by an
    nnz upper bound and ``argpartition`` allocates an int64 index array, and both
    scale with the number of rows. Measured on this dataset: peak RSS 1.3 GB with
    chunk=125 versus 3.3 GB for a plain 2,000-row sparse product, same 6-7 s.
    """
    n, n_train = X_query.shape[0], X_train.shape[0]
    nn_pos = np.zeros((n, k), dtype=np.int64)
    nn_sim = np.zeros((n, k), dtype=np.float32)
    X_train_t = X_train.T.tocsr()
    buffer = np.empty((min(block, n), n_train), dtype=np.float32)
    for start in range(0, n, block):
        stop = min(start + block, n)
        S = buffer[: stop - start]
        for c in range(0, stop - start, chunk):
            prod = X_query[start + c:min(start + c + chunk, stop)] @ X_train_t
            prod.toarray(out=S[c:c + prod.shape[0]])
        for c in range(0, stop - start, chunk):
            Sc = S[c:c + chunk]
            idx = np.argpartition(Sc, n_train - k, axis=1)[:, -k:]  # k largest, unordered
            sims = np.take_along_axis(Sc, idx, axis=1)
            order = np.argsort(-sims, axis=1, kind="stable")
            nn_pos[start + c:start + c + Sc.shape[0]] = np.take_along_axis(idx, order, axis=1)
            nn_sim[start + c:start + c + Sc.shape[0]] = np.take_along_axis(sims, order, axis=1)
    return nn_pos, np.clip(nn_sim, 0.0, 1.0)


# --------------------------------------------------------------------------- metrics
def per_class_report(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    rep = classification_report(y_true, y_pred, labels=CLASSES, output_dict=True, zero_division=0)
    return {
        c: {
            "precision": r4(rep[c]["precision"]),
            "recall": r4(rep[c]["recall"]),
            "f1": r4(rep[c]["f1-score"]),
            "support": int(rep[c]["support"]),
        }
        for c in CLASSES
    }


def expected_calibration_error(confidence: np.ndarray, correct: np.ndarray, n_bins: int = ECE_BINS) -> tuple[float, list[dict]]:
    """Equal-width ECE: sum_b (n_b / N) * |acc_b - conf_b|."""
    edges = np.linspace(0.0, 1.0, n_bins + 1)
    which = np.minimum((confidence * n_bins).astype(int), n_bins - 1)
    n = confidence.size
    ece = 0.0
    bins = []
    for b in range(n_bins):
        m = which == b
        nb = int(m.sum())
        row = {"lo": r4(edges[b]), "hi": r4(edges[b + 1]), "n": nb, "confidence": None, "accuracy": None}
        if nb:
            conf_b = float(confidence[m].mean())
            acc_b = float(correct[m].mean())
            ece += nb / n * abs(acc_b - conf_b)
            row.update(confidence=r4(conf_b), accuracy=r4(acc_b))
        bins.append(row)
    return r4(ece), bins


def threshold_curve(confidence: np.ndarray, correct: np.ndarray, pred: np.ndarray, has_risk: np.ndarray) -> list[dict]:
    """Raw and useful (policy-filtered) coverage x accuracy for every threshold."""
    n = confidence.size
    auto_ok = np.isin(pred, list(AUTO)) & ~has_risk
    rows = []
    for t in THRESHOLDS:
        covered = confidence >= t
        useful = covered & auto_ok
        rest = ~covered
        rows.append(
            {
                "t": float(t),
                "coverage": r4(covered.mean()),
                "n_covered": int(covered.sum()),
                "acc_covered": mean_or_none(correct[covered]),
                "n_errors_covered": int((~correct[covered]).sum()),
                "acc_rest": mean_or_none(correct[rest]),
                "n_rest": int(rest.sum()),
                "useful_coverage": r4(useful.sum() / n),
                "n_useful": int(useful.sum()),
                "useful_acc": mean_or_none(correct[useful]),
                "n_errors_useful": int((~correct[useful]).sum()),
            }
        )
    return rows


def per_class_at_thresholds(confidence: np.ndarray, correct: np.ndarray, pred: np.ndarray, y_true: np.ndarray) -> dict:
    """Per predicted class: share of its tickets above the threshold and their accuracy."""
    n = confidence.size
    out: dict[str, dict] = {}
    for t in POLICY_THRESHOLDS:
        table = {}
        for c in CLASSES:
            is_pred = pred == c
            covered = is_pred & (confidence >= t)
            n_pred = int(is_pred.sum())
            n_cov = int(covered.sum())
            table[c] = {
                "coverage": r4(n_cov / n_pred) if n_pred else 0.0,
                "acc": mean_or_none(correct[covered]),
                "n": n_cov,
                "n_pred": n_pred,
                "support": int((y_true == c).sum()),
                "n_errors": int((~correct[covered]).sum()),
                "share_of_all": r4(n_cov / n),
            }
        out[f"{t:.2f}"] = table
    return out


def similarity_metrics(nn_pos: np.ndarray, nn_sim: np.ndarray, y_train: np.ndarray, y_true: np.ndarray) -> dict:
    sim1 = nn_sim[:, 0].astype(np.float64)
    nn_correct = y_train[nn_pos[:, 0]] == y_true
    bins = []
    for b in SIM_BINS:
        m = sim1 >= b
        bins.append(
            {
                "min_sim": b,
                "coverage": r4(m.mean()),
                "n": int(m.sum()),
                "nn_agreement": mean_or_none(nn_correct[m]),
            }
        )
    return {
        "k": TOP_K,
        "nn_accuracy": r4(nn_correct.mean()),
        "sim1_mean": r4(sim1.mean()),
        "sim1_median": r4(np.median(sim1)),
        "bins": bins,
    }


def cross_validate_5fold(texts: np.ndarray, labels: np.ndarray) -> dict:
    pipe = Pipeline(
        [("tfidf", TfidfVectorizer(dtype=np.float32, **TFIDF_CONFIG)), ("clf", LogisticRegression(**LOGREG_CONFIG))]
    )
    cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=SEED)
    t0 = time.perf_counter()
    res = cross_validate(pipe, texts, labels, cv=cv, scoring=("accuracy", "f1_macro"), n_jobs=1)
    return {
        "folds": CV_FOLDS,
        "accuracy": r4(res["test_accuracy"].mean()),
        "accuracy_std": r4(res["test_accuracy"].std()),
        "macro_f1": r4(res["test_f1_macro"].mean()),
        "macro_f1_std": r4(res["test_f1_macro"].std()),
        "fold_accuracies": [r4(s) for s in res["test_accuracy"]],
        "seconds": r4(time.perf_counter() - t0),
    }


# --------------------------------------------------------------------------- figures
def _style(ax, title: str, subtitle: str, xlabel: str, ylabel: str) -> None:
    ax.set_title(title, loc="left", fontsize=11.5, color=INK, pad=20)
    ax.text(0, 1.02, subtitle, transform=ax.transAxes, ha="left", va="bottom", fontsize=8.5, color=GRAY)
    ax.set_xlabel(xlabel, color=INK)
    ax.set_ylabel(ylabel, color=INK)
    ax.grid(color=GRID, linewidth=0.6)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRAY)
    ax.tick_params(colors=INK, labelsize=8.5)


def _new_figure(size=(9, 5.2)):
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=size, dpi=150)
    fig.patch.set_facecolor(SURFACE)
    ax.set_facecolor(SURFACE)
    return plt, fig, ax


def _save(plt, fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, facecolor=SURFACE)
    plt.close(fig)


def plot_confusion(matrix: np.ndarray, accuracy: float, n: int) -> None:
    from matplotlib.colors import LinearSegmentedColormap

    plt, fig, ax = _new_figure((8.6, 7.2))
    row_sums = matrix.sum(axis=1, keepdims=True)
    norm = np.divide(matrix, row_sums, out=np.zeros_like(matrix, dtype=float), where=row_sums > 0)
    cmap = LinearSegmentedColormap.from_list("navy_seq", [SURFACE, NAVY])
    ax.imshow(norm, cmap=cmap, vmin=0, vmax=1)
    k = len(CLASSES)
    ax.set_xticks(range(k), CLASSES, rotation=35, ha="right")
    ax.set_yticks(range(k), CLASSES)
    for i in range(k):
        for j in range(k):
            if matrix[i, j] == 0:
                continue
            color = SURFACE if norm[i, j] > 0.55 else INK
            ax.text(j, i, f"{norm[i, j]:.0%}\n{matrix[i, j]:,}".replace(",", "."), ha="center", va="center",
                    fontsize=7.5, color=color)
    n_txt = f"{n:,}".replace(",", ".")
    _style(ax, "Matriz de confusão do hold-out (normalizada por linha)",
           f"acurácia {pct(accuracy)} · n = {n_txt} tickets · linha = classe verdadeira, coluna = prevista",
           "classe prevista", "classe verdadeira")
    ax.grid(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_visible(False)
    _save(plt, fig, FIGURES["confusion"])


def plot_coverage_accuracy(rows: list[dict]) -> None:
    plt, fig, ax = _new_figure()
    cov = [r["coverage"] for r in rows]
    acc = [r["acc_covered"] for r in rows]
    ucov = [r["useful_coverage"] for r in rows]
    uacc = [r["useful_acc"] for r in rows]
    ax.plot(cov, acc, color=NAVY, linewidth=2, marker="o", markersize=3.5, label="cobertura bruta (p ≥ limiar)")
    ax.plot(ucov, uacc, color=GOLD, linewidth=2, marker="s", markersize=3.5,
            label="cobertura útil (p ≥ limiar, classe AUTO, sem sinal de risco)")
    for t in POLICY_THRESHOLDS:
        r = next(x for x in rows if abs(x["t"] - t) < 1e-9)
        label = f"limiar {t:.2f}".replace(".", ",")
        # raw series: label above-right; useful series: below-left, so labels never cross the other line
        for x, y, xytext, ha in ((r["coverage"], r["acc_covered"], (7, 7), "left"),
                                 (r["useful_coverage"], r["useful_acc"], (-8, -12), "right")):
            ax.annotate(label, (x, y), textcoords="offset points", xytext=xytext, ha=ha, fontsize=8, color=INK)
            ax.plot([x], [y], marker="o", markersize=8, markerfacecolor="none", markeredgecolor=DANGER, linewidth=0)
    ax.text(cov[0], acc[0], "  bruta", color=NAVY, fontsize=8.5, va="center")
    ax.text(ucov[0], uacc[0], "  útil", color=GOLD, fontsize=8.5, va="center")
    ax.set_xlim(0, 1)
    lo = min(min(a for a in acc if a is not None), min(a for a in uacc if a is not None))
    ax.set_ylim(max(0.0, lo - 0.03), 1.005)
    ax.xaxis.set_major_formatter(lambda v, _: f"{v:.0%}")
    ax.yaxis.set_major_formatter(lambda v, _: f"{v:.0%}")
    ax.legend(loc="lower left", frameon=False, fontsize=8.5)
    _style(ax, "Cobertura × acerto por limiar de confiança",
           "hold-out · cada ponto é um limiar de 0,50 a 0,99 · círculos vermelhos: 0,80 / 0,90 / 0,95",
           "fração dos tickets roteados sozinhos pela IA", "acerto entre os tickets roteados")
    _save(plt, fig, FIGURES["coverage_accuracy"])


def plot_reliability(bins: list[dict], ece: float) -> None:
    plt, fig, ax = _new_figure((7.5, 5.6))
    width = 1.0 / len(bins)
    centers = [(b["lo"] + b["hi"]) / 2 for b in bins]
    accs = [b["accuracy"] if b["accuracy"] is not None else 0.0 for b in bins]
    ax.bar(centers, accs, width=width * 0.92, color=NAVY, edgecolor=SURFACE, linewidth=1, label="acerto observado no bin")
    ax.plot([0, 1], [0, 1], linestyle="--", color=GRAY, linewidth=1.4, label="calibração perfeita")
    for c, b in zip(centers, bins):
        if b["n"]:
            ax.text(c, (b["accuracy"] or 0) + 0.015, f"n={b['n']:,}".replace(",", "."), ha="center", va="bottom",
                    fontsize=7.5, color=INK)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.08)
    ax.xaxis.set_major_formatter(lambda v, _: f"{v:.1f}".replace(".", ","))
    ax.yaxis.set_major_formatter(lambda v, _: f"{v:.0%}")
    ax.legend(loc="upper left", frameon=False, fontsize=8.5)
    _style(ax, "Diagrama de confiabilidade (calibração da confiança)",
           f"hold-out · {len(bins)} bins de largura igual · ECE = {ece:.3f}".replace(".", ","),
           "confiança prevista (máxima probabilidade)", "acerto observado")
    _save(plt, fig, FIGURES["reliability"])


def plot_similarity(sim: dict) -> None:
    plt, fig, ax = _new_figure()
    xs = [b["min_sim"] for b in sim["bins"]]
    cov = [b["coverage"] for b in sim["bins"]]
    agr = [b["nn_agreement"] if b["nn_agreement"] is not None else np.nan for b in sim["bins"]]
    ax.plot(xs, cov, color=NAVY, linewidth=2, marker="o", markersize=5, label="cobertura (similaridade do 1º vizinho ≥ x)")
    ax.plot(xs, agr, color=GOLD, linewidth=2, marker="s", markersize=5, label="concordância: classe do 1º vizinho = verdadeira")
    for x, c, a in zip(xs, cov, agr):
        # coverage labels sit below the point; the last, near-zero points go above so they stay off the axis
        ax.annotate(pct(c), (x, c), textcoords="offset points", xytext=(0, -14 if c > 0.06 else 7),
                    ha="center", fontsize=7.5, color=NAVY)
        if not np.isnan(a):
            ax.annotate(pct(a), (x, a), textcoords="offset points", xytext=(0, 7), ha="center", fontsize=7.5, color=GOLD)
    ax.axvline(0.9, color=DANGER, linestyle="--", linewidth=1.2)
    ax.text(0.893, 0.55, "≥ 0,90: regra de\n\"aplicar tratativa\"", color=DANGER, fontsize=8, ha="right", va="center")
    ax.set_xlim(0.25, 1.02)
    ax.set_ylim(0, 1.18)
    ax.xaxis.set_major_formatter(lambda v, _: f"{v:.2f}".replace(".", ","))
    ax.yaxis.set_major_formatter(lambda v, _: f"{v:.0%}")
    ax.legend(loc="upper left", frameon=False, fontsize=8.5)
    _style(ax, "Similaridade com o histórico: cobertura e concordância do 1-NN",
           f"hold-out × treino · cosseno sobre TF-IDF · acerto global do 1-NN = {pct(sim['nn_accuracy'])}",
           "similaridade mínima do vizinho mais próximo", "fração dos tickets do hold-out")
    _save(plt, fig, FIGURES["similarity_curve"])


# --------------------------------------------------------------------------- outputs
def write_holdout_csv(ids: np.ndarray, texts: np.ndarray, y_true: np.ndarray, pred: np.ndarray,
                      confidence: np.ndarray, top3: list[list[dict]], nn_ids: np.ndarray, nn_sim: np.ndarray) -> None:
    out = pd.DataFrame(
        {
            "id": ids.astype(int),
            "text": texts,
            "true_category": y_true,
            "pred_category": pred,
            "confidence": confidence,
            "top3_json": [json.dumps(t, ensure_ascii=False) for t in top3],
            "nn_ids_json": [json.dumps([int(v) for v in row]) for row in nn_ids],
            "nn_sims_json": [json.dumps([r4(v) for v in row]) for row in nn_sim],
        },
        columns=HOLDOUT_COLUMNS,
    )
    # mtime=0 keeps the gzip bytes reproducible for identical content (less git churn).
    out.to_csv(HOLDOUT, index=False, compression={"method": "gzip", "compresslevel": 6, "mtime": 0})


def main(run_cv5: bool = True) -> dict:
    if not DATA.exists():
        sys.exit(f"missing {DATA} - run `make data` first")
    t_start = time.perf_counter()

    df, n_total, n_removed = load_and_dedup()
    tr, ho = split(df)
    texts = df[TEXT_COL].to_numpy()
    labels = df[LABEL_COL].to_numpy()
    ids = df.index.to_numpy()
    print(f"rows={n_total} dedup_removed={n_removed} train={tr.size} holdout={ho.size}")

    t0 = time.perf_counter()
    vec, clf, X_train = fit(texts[tr], labels[tr])
    fit_seconds = time.perf_counter() - t0
    print(f"tfidf features={X_train.shape[1]} nnz={X_train.nnz} · fit {fit_seconds:.1f}s")

    X_hold = vec.transform(texts[ho]).tocsr()
    proba, pred, confidence, top3 = predict(clf, X_hold)
    y_true = labels[ho]
    correct = pred == y_true

    t0 = time.perf_counter()
    nn_pos, nn_sim = nearest_neighbors(X_hold, X_train)
    sim_seconds = time.perf_counter() - t0
    nn_ids = ids[tr][nn_pos]
    print(f"neighbors (blocks of {SIM_BLOCK}) {sim_seconds:.1f}s")

    has_risk = np.array([bool(risk_flags(t)) for t in texts[ho]], dtype=bool)
    accuracy = r4(accuracy_score(y_true, pred))
    macro_f1 = r4(f1_score(y_true, pred, average="macro"))
    ece, calib_bins = expected_calibration_error(confidence, correct)
    thresholds = threshold_curve(confidence, correct, pred, has_risk)
    per_class_at = per_class_at_thresholds(confidence, correct, pred, y_true)
    sim = similarity_metrics(nn_pos, nn_sim, labels[tr], y_true)
    cm = confusion_matrix(y_true, pred, labels=CLASSES)

    cv5 = None
    if run_cv5:
        if fit_seconds * CV_FOLDS <= CV_BUDGET_SECONDS:
            cv5 = cross_validate_5fold(texts, labels)
            print(f"cv5 accuracy={cv5['accuracy']:.4f} macro_f1={cv5['macro_f1']:.4f} ({cv5['seconds']:.0f}s)")
        else:
            print(f"cv5 skipped: {CV_FOLDS} fits of ~{fit_seconds:.0f}s exceed the {CV_BUDGET_SECONDS}s budget")

    plot_confusion(cm, accuracy, ho.size)
    plot_coverage_accuracy(thresholds)
    plot_reliability(calib_bins, ece)
    plot_similarity(sim)

    ART.mkdir(parents=True, exist_ok=True)
    MODELS.mkdir(parents=True, exist_ok=True)
    write_holdout_csv(ids[ho], texts[ho], y_true, pred, confidence, top3, nn_ids, nn_sim)
    POLICY.write_text(json.dumps(policy_table(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    trained_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    config = {
        "dataset": {"file": DATA.name, "sha256": sha256(DATA), "text_column": TEXT_COL, "label_column": LABEL_COL},
        "text_normalization": "none: dataset text is pre-processed; app.normalize applies to free text in the API",
        "dedup_key": f"first {DEDUP_WORDS} words, keep first occurrence",
        "split": {"test_size": TEST_SIZE, "stratify": True, "random_state": SEED},
        "tfidf": {**TFIDF_CONFIG, "dtype": "float32"},
        "logreg": LOGREG_CONFIG,
        "similarity": {"metric": "cosine on TF-IDF (rows L2-normalized)", "k": TOP_K, "block_rows": SIM_BLOCK},
        "ids": "0-based row index of the CSV before dedup; nn_ids are values of train_ids, not positions in X_train",
        "default_threshold": DEFAULT_THRESHOLD,
        "auto_classes": sorted(AUTO),
        "ece_bins": ECE_BINS,
        "seed": SEED,
    }
    # Pickle produced here, on the maintainer's machine, and loaded only by app.model from the
    # project's own models/ directory (gitignored, regenerated by `make train`). Never load a
    # pickle from an untrusted source: it can execute arbitrary code.
    joblib.dump(
        {
            "vectorizer": vec,
            "clf": clf,
            "X_train": X_train.astype(np.float32),
            "train_ids": ids[tr].astype(np.int64),
            "train_texts": [str(t) for t in texts[tr]],
            "train_labels": labels[tr].astype(str),
            "classes": list(CLASSES),
            "config": config,
            "trained_at": trained_at,
        },
        INDEX,
        compress=3,
    )
    pickle_bytes = INDEX.stat().st_size

    metrics = {
        "generated_at": trained_at,
        "config": config,
        "n_total": n_total,
        "n_dedup_removed": n_removed,
        "n_train": int(tr.size),
        "n_holdout": int(ho.size),
        "n_features": int(X_train.shape[1]),
        "class_counts": {c: int((labels == c).sum()) for c in CLASSES},
        "accuracy": accuracy,
        "macro_f1": macro_f1,
        "ece": ece,
        "per_class": per_class_report(y_true, pred),
        "confusion": {"labels": list(CLASSES), "matrix": cm.astype(int).tolist()},
        "thresholds": thresholds,
        "per_class_at": per_class_at,
        "similarity": sim,
        "calibration": {"n_bins": ECE_BINS, "bins": calib_bins},
        "risk_flag_share_holdout": r4(has_risk.mean()),
        "runtime": {
            "fit_seconds": r4(fit_seconds),
            "similarity_seconds": r4(sim_seconds),
            "cv5_seconds": cv5["seconds"] if cv5 else None,
            "train_seconds_total": r4(time.perf_counter() - t_start),
            "peak_rss_mb": peak_rss_mb(),
            "pickle_bytes": int(pickle_bytes),
        },
        "figures": {k: str(v.relative_to(PROTO)) for k, v in FIGURES.items()},
    }
    if cv5:
        metrics["cv5"] = cv5
    METRICS.write_text(json.dumps(metrics, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    row90 = next(r for r in thresholds if abs(r["t"] - DEFAULT_THRESHOLD) < 1e-9)
    print(f"accuracy={accuracy:.4f} macro_f1={macro_f1:.4f} ece={ece:.4f} nn_accuracy={sim['nn_accuracy']:.4f}")
    for t in POLICY_THRESHOLDS:
        r = next(x for x in thresholds if abs(x["t"] - t) < 1e-9)
        print(f"t={t:.2f}: coverage={r['coverage']:.3f} acc={r['acc_covered']:.4f} "
              f"useful={r['useful_coverage']:.3f} useful_acc={r['useful_acc']:.4f} errors={r['n_errors_useful']}")
    print(f"total {metrics['runtime']['train_seconds_total']:.1f}s · peak rss {metrics['runtime']['peak_rss_mb']:.0f} MB "
          f"· pickle {pickle_bytes / 1e6:.1f} MB · useful coverage at {DEFAULT_THRESHOLD:.2f} = {row90['useful_coverage']:.3f}")
    print(f"wrote {METRICS.relative_to(PROTO)}, {POLICY.relative_to(PROTO)}, {HOLDOUT.relative_to(PROTO)}, "
          f"{INDEX.relative_to(PROTO)} and {len(FIGURES)} figures")
    return metrics


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--no-cv5", action="store_true", help="skip the optional 5-fold cross-validation")
    args = parser.parse_args()
    main(run_cv5=not args.no_cv5)
